server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.61.140:3306/tensquare_recruit?useSSL=false&characterEncoding=utf-8
    username: root
    password: Lj586492
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true
